events { worker_connections 1024; }

http {
    upstream user_service    { server user-service:8001; }
    upstream property_service { server property-service:8002; }
    upstream booking_service  { server booking-service:8003; }

    server {
        listen 80;

        location /api/v1/auth/ {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/properties/ {
            proxy_pass http://property_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/bookings/ {
            proxy_pass http://booking_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 '{"status":"ok","service":"nginx"}';
            add_header Content-Type application/json;
        }
    }
}
